private ["_class", "_unit"];

_class = _this;
_unit = player;

if (local _unit) then {
	switch ( _class ) do {
		case "Rifleman": {
			removeAllWeapons _unit;
			removeAllItems _unit;
			removeAllAssignedItems _unit;
			removeUniform _unit;
			removeVest _unit;
			removeBackpack _unit;
			removeHeadgear _unit;
			removeGoggles _unit;
			_unit forceAddUniform "U_B_CTRG_1";
			for "_i" from 1 to 5 do {_unit addItemToUniform "FirstAidKit";};
			_unit addVest "V_PlateCarrierH_CTRG";
			for "_i" from 1 to 6 do {_unit addItemToVest "30Rnd_65x39_caseless_mag";};
			for "_i" from 1 to 4 do {_unit addItemToVest "HandGrenade";};
			for "_i" from 1 to 4 do {_unit addItemToVest "SmokeShell";};
			for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShellBlue";};
			for "_i" from 1 to 2 do {_unit addItemToVest "16Rnd_9x21_Mag";};
			_unit addBackpack "B_Carryall_cbr";
			for "_i" from 1 to 8 do {_unit addItemToBackpack "FirstAidKit";};
			for "_i" from 1 to 6 do {_unit addItemToBackpack "30Rnd_65x39_caseless_mag";};
			_unit addItemToBackpack "B_IR_Grenade";
			for "_i" from 1 to 2 do {_unit addItemToBackpack "Chemlight_blue";};
			_unit addHeadgear "H_HelmetSpecB";
			_unit addWeapon "arifle_MX_Black_F";
			_unit addPrimaryWeaponItem "acc_flashlight";
			_unit addPrimaryWeaponItem "optic_Hamr";
			_unit addWeapon "hgun_P07_F";
			_unit addWeapon "Binocular";
			_unit linkItem "ItemMap";
			_unit linkItem "ItemCompass";
			_unit linkItem "ItemWatch";
			_unit linkItem "ItemRadio";
			_unit linkItem "ItemGPS";
			_unit linkItem "NVGoggles";
		};
		case "Medic": {
			removeAllWeapons _unit;
			removeAllItems _unit;
			removeAllAssignedItems _unit;
			removeUniform _unit;
			removeVest _unit;
			removeBackpack _unit;
			removeHeadgear _unit;
			removeGoggles _unit;
			_unit forceAddUniform "U_B_CTRG_3";
			for "_i" from 1 to 6 do {_unit addItemToUniform "SmokeShell";};
			_unit addVest "V_PlateCarrierL_CTRG";
			for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShellBlue";};
			for "_i" from 1 to 2 do {_unit addItemToVest "HandGrenade";};
			for "_i" from 1 to 2 do {_unit addItemToVest "16Rnd_9x21_Mag";};
			for "_i" from 1 to 3 do {_unit addItemToVest "30Rnd_65x39_caseless_mag";};
			for "_i" from 1 to 6 do {_unit addItemToVest "1Rnd_Smoke_Grenade_shell";};
			for "_i" from 1 to 4 do {_unit addItemToVest "1Rnd_HE_Grenade_shell";};
			for "_i" from 1 to 2 do {_unit addItemToVest "SmokeShell";};
			_unit addBackpack "B_Carryall_cbr";
			_unit addItemToBackpack "Medikit";
			for "_i" from 1 to 8 do {_unit addItemToBackpack "FirstAidKit";};
			_unit addItemToBackpack "B_IR_Grenade";
			for "_i" from 1 to 2 do {_unit addItemToBackpack "Chemlight_blue";};
			for "_i" from 1 to 8 do {_unit addItemToBackpack "30Rnd_65x39_caseless_mag";};
			_unit addHeadgear "H_HelmetSpecB";
			_unit addWeapon "arifle_MX_GL_Black_F";
			_unit addPrimaryWeaponItem "acc_flashlight";
			_unit addPrimaryWeaponItem "optic_Hamr";
			_unit addWeapon "hgun_P07_F";
			_unit addWeapon "Binocular";
			_unit linkItem "ItemMap";
			_unit linkItem "ItemCompass";
			_unit linkItem "ItemWatch";
			_unit linkItem "ItemRadio";
			_unit linkItem "ItemGPS";
			_unit linkItem "NVGoggles";
		};
		case "Marksman": {
			removeAllWeapons _unit;
			removeAllItems _unit;
			removeAllAssignedItems _unit;
			removeUniform _unit;
			removeVest _unit;
			removeBackpack _unit;
			removeHeadgear _unit;
			removeGoggles _unit;
			_unit forceAddUniform "U_B_CTRG_1";
			for "_i" from 1 to 5 do {_unit addItemToUniform "FirstAidKit";};
			_unit addVest "V_PlateCarrierH_CTRG";
			for "_i" from 1 to 8 do {_unit addItemToVest "20Rnd_762x51_Mag";};
			for "_i" from 1 to 2 do {_unit addItemToVest "16Rnd_9x21_Mag";};
			_unit addBackpack "B_Carryall_cbr";
			for "_i" from 1 to 8 do {_unit addItemToBackpack "FirstAidKit";};
			_unit addItemToBackpack "B_IR_Grenade";
			for "_i" from 1 to 2 do {_unit addItemToBackpack "Chemlight_blue";};
			for "_i" from 1 to 8 do {_unit addItemToBackpack "20Rnd_762x51_Mag";};
			for "_i" from 1 to 4 do {_unit addItemToBackpack "HandGrenade";};
			for "_i" from 1 to 4 do {_unit addItemToBackpack "SmokeShell";};
			for "_i" from 1 to 2 do {_unit addItemToBackpack "SmokeShellBlue";};
			for "_i" from 1 to 2 do {_unit addItemToBackpack "16Rnd_9x21_Mag";};
			_unit addHeadgear "H_Booniehat_khk";
			_unit addWeapon "srifle_EBR_F";
			_unit addPrimaryWeaponItem "acc_flashlight";
			_unit addPrimaryWeaponItem "optic_AMS";
			_unit addPrimaryWeaponItem "bipod_01_F_blk";
			_unit addWeapon "hgun_P07_F";
			_unit addWeapon "Rangefinder";
			_unit linkItem "ItemMap";
			_unit linkItem "ItemCompass";
			_unit linkItem "ItemWatch";
			_unit linkItem "ItemRadio";
			_unit linkItem "ItemGPS";
			_unit linkItem "NVGoggles";
		};
		case "Engineer": {
			removeAllWeapons _unit;
			removeAllItems _unit;
			removeAllAssignedItems _unit;
			removeUniform _unit;
			removeVest _unit;
			removeBackpack _unit;
			removeHeadgear _unit;
			removeGoggles _unit;
			_unit forceAddUniform "U_B_CTRG_1";
			for "_i" from 1 to 5 do {_unit addItemToUniform "FirstAidKit";};
			_unit addVest "V_PlateCarrierH_CTRG";
			for "_i" from 1 to 8 do {_unit addItemToVest "30Rnd_65x39_caseless_mag";};
			for "_i" from 1 to 2 do {_unit addItemToVest "16Rnd_9x21_Mag";};
			for "_i" from 1 to 2 do {_unit addItemToVest "HandGrenade";};
			_unit addItemToVest "SmokeShell";
			_unit addBackpack "B_Carryall_cbr";
			for "_i" from 1 to 8 do {_unit addItemToBackpack "FirstAidKit";};
			_unit addItemToBackpack "ToolKit";
			_unit addItemToBackpack "B_IR_Grenade";
			for "_i" from 1 to 2 do {_unit addItemToBackpack "Chemlight_blue";};
			for "_i" from 1 to 4 do {_unit addItemToBackpack "30Rnd_65x39_caseless_mag";};
			_unit addItemToBackpack "SatchelCharge_Remote_Mag";
			for "_i" from 1 to 2 do {_unit addItemToBackpack "DemoCharge_Remote_Mag";};
			_unit addHeadgear "H_Watchcap_khk";
			_unit addWeapon "arifle_MX_Black_F";
			_unit addPrimaryWeaponItem "acc_flashlight";
			_unit addPrimaryWeaponItem "optic_Hamr";
			_unit addWeapon "hgun_P07_F";
			_unit addWeapon "Binocular";
			_unit linkItem "ItemMap";
			_unit linkItem "ItemCompass";
			_unit linkItem "ItemWatch";
			_unit linkItem "ItemRadio";
			_unit linkItem "ItemGPS";
			_unit linkItem "NVGoggles";
		};
		case "Machinegunner": {
			removeAllWeapons _unit;
			removeAllItems _unit;
			removeAllAssignedItems _unit;
			removeUniform _unit;
			removeVest _unit;
			removeBackpack _unit;
			removeHeadgear _unit;
			removeGoggles _unit;
			_unit forceAddUniform "U_B_CTRG_2";
			for "_i" from 1 to 5 do {_unit addItemToUniform "FirstAidKit";};
			_unit addVest "V_PlateCarrierL_CTRG";
			for "_i" from 1 to 8 do {_unit addItemToVest "FirstAidKit";};
			for "_i" from 1 to 4 do {_unit addItemToVest "HandGrenade";};
			for "_i" from 1 to 4 do {_unit addItemToVest "SmokeShell";};
			_unit addBackpack "B_Carryall_cbr";
			for "_i" from 1 to 6 do {_unit addItemToBackpack "130Rnd_338_Mag";};
			_unit addHeadgear "H_Cap_khaki_specops_UK";
			_unit addWeapon "MMG_02_sand_F";
			_unit addPrimaryWeaponItem "acc_flashlight";
			_unit addPrimaryWeaponItem "optic_Arco";
			_unit addPrimaryWeaponItem "bipod_01_F_snd";
			_unit addWeapon "Binocular";
			_unit linkItem "ItemMap";
			_unit linkItem "ItemCompass";
			_unit linkItem "ItemWatch";
			_unit linkItem "ItemRadio";
			_unit linkItem "ItemGPS";
			_unit linkItem "NVGoggles";
		};
		case "Pilot": {
			removeAllWeapons _unit;
			removeAllItems _unit;
			removeAllAssignedItems _unit;
			removeUniform _unit;
			removeVest _unit;
			removeBackpack _unit;
			removeHeadgear _unit;
			removeGoggles _unit;
			_unit forceAddUniform "U_B_PilotCoveralls";
			for "_i" from 1 to 2 do {_unit addItemToUniform "FirstAidKit";};
			for "_i" from 1 to 4 do {_unit addItemToUniform "30Rnd_65x39_caseless_mag";};
			_unit addHeadgear "H_PilotHelmetFighter_B";
			_unit addWeapon "arifle_MXC_Black_F";
			_unit addPrimaryWeaponItem "optic_Aco";
			_unit addWeapon "Binocular";
			_unit linkItem "ItemMap";
			_unit linkItem "ItemCompass";
			_unit linkItem "ItemWatch";
			_unit linkItem "ItemRadio";
			_unit linkItem "B_UavTerminal";
			_unit linkItem "NVGoggles";
		};
		case "Sniper (.338)": {
			removeAllWeapons _unit;
			removeAllItems _unit;
			removeAllAssignedItems _unit;
			removeUniform _unit;
			removeVest _unit;
			removeBackpack _unit;
			removeHeadgear _unit;
			removeGoggles _unit;
			_unit forceAddUniform "U_B_FullGhillie_sard";
			for "_i" from 1 to 2 do {_unit addItemToUniform "FirstAidKit";};
			for "_i" from 1 to 2 do {_unit addItemToUniform "11Rnd_45ACP_Mag";};
			for "_i" from 1 to 2 do {_unit addItemToUniform "10Rnd_338_Mag";};
			_unit addItemToUniform "B_IR_Grenade";
			_unit addItemToUniform "Laserbatteries";
			_unit addVest "V_PlateCarrierH_CTRG";
			for "_i" from 1 to 8 do {_unit addItemToVest "10Rnd_338_Mag";};
			_unit addGoggles "G_Bandanna_khk";
			_unit addWeapon "srifle_DMR_02_sniper_F";
			_unit addPrimaryWeaponItem "muzzle_snds_338_sand";
			_unit addPrimaryWeaponItem "acc_flashlight";
			_unit addPrimaryWeaponItem "optic_AMS_snd";
			_unit addPrimaryWeaponItem "bipod_01_F_snd";
			_unit addWeapon "hgun_Pistol_heavy_01_F";
			_unit addHandgunItem "muzzle_snds_acp";
			_unit addHandgunItem "optic_MRD";
			_unit addWeapon "Laserdesignator";
			_unit linkItem "ItemMap";
			_unit linkItem "ItemCompass";
			_unit linkItem "ItemWatch";
			_unit linkItem "ItemRadio";
			_unit linkItem "ItemGPS";
			_unit linkItem "NVGoggles";
		};
		case "Sniper (.408)": {
			removeAllWeapons _unit;
			removeAllItems _unit;
			removeAllAssignedItems _unit;
			removeUniform _unit;
			removeVest _unit;
			removeBackpack _unit;
			removeHeadgear _unit;
			removeGoggles _unit;
			_unit forceAddUniform "U_B_FullGhillie_sard";
			for "_i" from 1 to 2 do {_unit addItemToUniform "FirstAidKit";};
			for "_i" from 1 to 2 do {_unit addItemToUniform "9Rnd_45ACP_Mag";};
			for "_i" from 1 to 2 do {_unit addItemToUniform "7Rnd_408_Mag";};
			_unit addVest "V_PlateCarrierH_CTRG";
			_unit addItemToUniform "Laserbatteries";
			for "_i" from 1 to 10 do {_unit addItemToVest "7Rnd_408_Mag";};
			_unit addItemToVest "B_IR_Grenade";
			_unit addGoggles "G_Bandanna_khk";
			_unit addWeapon "srifle_LRR_F";
			_unit addPrimaryWeaponItem "optic_LRPS";
			_unit addWeapon "hgun_ACPC2_F";
			_unit addWeapon "Laserdesignator";
			_unit linkItem "ItemMap";
			_unit linkItem "ItemCompass";
			_unit linkItem "ItemWatch";
			_unit linkItem "ItemRadio";
			_unit linkItem "ItemGPS";
			_unit linkItem "NVGoggles";
		};
	};
	
	_unit call fn_savePlayer;
};